### ISSUE TITLE
data_fusion of CUB200

### ISSUE THREAD

**Issue by wusuoweima** [CanPeng123/FSCIL_ALICE#5]
Why is not ''--data_fusion'' in run_base_CUB200.sh?
@CanPeng123

**Comment by CanPeng123** [comment]
Hi,

For experiments on the CUB200 dataset, we find that applying class augmentation will deteriorate the model performance. As CUB200 is a fine-grained dataset, the feature extractor needs to focus on learning tiny differences between categories. However, class augmentation targets obscuring the class difference and forcing the feature extractor to focus on general features. It is a good augmentation strategy to extract transferable features for general FSCIL tasks but will adversely obscure the class boundaries for fine-grained FSCIL tasks. Thus, for experiments on CUB200, we do not use class augmentation and train the feature extractor only by angular penalty and data augmentation. 

You can find a more detailed explanation of this in our main manuscript section 5.3 Comparison with the State-of-the-art Methods second paragraph.

Hope this could clarify your confusion.
