### ISSUE TITLE
Regarding protocol for evaluating FSCIL performance

### ISSUE THREAD

**Issue by prachigarg23** [CanPeng123/FSCIL_ALICE#6]
Hi @CanPeng123 , thanks for your amazing work and code. I wanted to confirm if in FSCIL, the standard is to fix the 5-shots selected for all incremental steps and as long as its consistent across all experimental comparisons and released along with code, only a single-run on the 5 shots is reported right? There is no average across multiple runs where each run is trained using a different set of 5 shots?

**Comment by CanPeng123** [comment]
Hi, thanks for your interest in our work. 
Yes, currently most FSCIL papers follow the same data-loading strategy provided by the previous SOTA paper. To make the comparison fair, we also follow the same data-loading approach. No average across multiple runs with different 5-shot data is used. However, multiple runs with different few-shot could be more comprehensive to validate the effectiveness of the method which could be utilized in future papers.
